# Generated by Django 5.1 on 2024-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="licence_code",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("", "Licence Codes"),
                    (1, "Code A"),
                    (2, "Code B"),
                    (3, "Code C"),
                    (4, "Code E"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="licence_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Learner", "Learners Licence Student"),
                    ("Driver", "Drivers Licence Student"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
