# Generated by Django 5.1 on 2024-08-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="licence_code",
            field=models.IntegerField(
                choices=[
                    ("", "Licence Codes"),
                    (1, "Code A"),
                    (2, "Code B"),
                    (3, "Code C"),
                    (4, "Code E"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=250),
        ),
    ]
