# Generated by Django 5.1 on 2024-09-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_category_remove_question_quiz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
