# Generated by Django 5.1 on 2024-09-03 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="test_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_no",
                to="app.testnumber",
            ),
        ),
    ]
