# Generated by Django 5.1 on 2024-09-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_testnumber_category_test_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testnumber",
            name="test",
            field=models.IntegerField(default=0),
        ),
    ]
