# Generated by Django 5.1 on 2024-09-03 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_alter_testnumber_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
