# Generated by Django 5.1 on 2024-09-03 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0010_alter_question_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="test_number",
        ),
        migrations.AddField(
            model_name="question",
            name="test_number",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_no",
                to="app.testnumber",
            ),
        ),
    ]
