# Generated by Django 5.1 on 2024-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0012_alter_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(max_length=1000),
        ),
    ]
