# Generated by Django 5.1 on 2024-09-05 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0013_alter_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
